### ISSUE TITLE
Event Outcome Note Error

### ISSUE THREAD

**Issue by AlicePrael** [ucancallmealicia/born-digital-accessioner#2]
The tool failed to import when the event outcome note stated "Read Error, Sync Error, 77.2% captured"
The archival object was created, but the event record was not created. The error log for this import is copied below. The GUI said "Updates finished!" so it wasn't until I checked Aspace that I noticed the failure to import.

Thanks!
Alice

2018-11-20 15:53:20,078 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:20,493 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "GET /api/users/current-user HTTP/1.1" 200 None
2018-11-20 15:53:20,493 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:20,893 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "GET /api/repositories HTTP/1.1" 200 None
2018-11-20 15:53:20,909 DEBUG root Setting resource ID
2018-11-20 15:53:20,909 DEBUG root 5353
2018-11-20 15:53:20,909 DEBUG root Setting parent ID
2018-11-20 15:53:20,909 DEBUG root 2119178
2018-11-20 15:53:20,909 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:21,364 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "GET /api/repositories/11/archival_objects/2119178 HTTP/1.1" 200 None
2018-11-20 15:53:21,375 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:21,791 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "GET /api/repositories/11/top_containers/226517 HTTP/1.1" 200 None
2018-11-20 15:53:21,806 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:22,273 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "GET /api/repositories/11/top_containers/226518 HTTP/1.1" 200 None
2018-11-20 15:53:22,286 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:22,713 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "GET /api/repositories/11/top_containers/226519 HTTP/1.1" 200 None
2018-11-20 15:53:22,729 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:23,170 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "GET /api/repositories/11/top_containers/226520 HTTP/1.1" 200 None
2018-11-20 15:53:23,181 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:23,614 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "GET /api/repositories/11/top_containers/226521 HTTP/1.1" 200 None
2018-11-20 15:53:23,630 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:24,077 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "GET /api/repositories/11/top_containers/226522 HTTP/1.1" 200 None
2018-11-20 15:53:24,077 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:24,527 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "GET /api/repositories/11/top_containers/226523 HTTP/1.1" 200 None
2018-11-20 15:53:24,539 DEBUG root Working on row 1
2018-11-20 15:53:24,540 DEBUG root Matching top_containers
2018-11-20 15:53:24,540 DEBUG root Container match not found
2018-11-20 15:53:24,540 DEBUG root Container match not found
2018-11-20 15:53:24,541 DEBUG root Container match not found
2018-11-20 15:53:24,541 DEBUG root Container match not found
2018-11-20 15:53:24,541 DEBUG root Container match not found
2018-11-20 15:53:24,541 DEBUG root Container match not found
2018-11-20 15:53:24,542 DEBUG root Container match not found
2018-11-20 15:53:24,542 DEBUG root Calling action function
2018-11-20 15:53:24,547 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:24,944 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "POST /api/repositories/11/archival_objects HTTP/1.1" 400 1191
2018-11-20 15:53:24,950 DEBUG root Finishing action function
2018-11-20 15:53:24,950 DEBUG root Error: {'error': {'instances/0/sub_container/top_container/ref': ['Must be a JSONModel(:top_container) uri (you provided a String) (malformed or invalid uri? check if referenced object exists.)']}, 'warning': None, 'invalid_object': '#<JSONModel(:archival_object) {"publish"=>true, "title"=>"IRA COHEN 70th Birthday Reading Zebulon, Brooklyn, NY February 3, 2005", "level"=>"item", "component_id"=>"2011-ycal-48482-0245", "jsonmodel_type"=>"archival_object", "extents"=>[{"number"=>"1", "portion"=>"whole", "extent_type"=>"CD-Rs", "jsonmodel_type"=>"extent"}], "instances"=>[{"instance_type"=>"mixed_materials", "jsonmodel_type"=>"instance", "sub_container"=>{"jsonmodel_type"=>"sub_container", "top_container"=>{"ref"=>"218: Series 11 [39002091569153]"}}, "is_representative"=>false}], "resource"=>{"ref"=>"/repositories/11+/resources/5353"}, "parent"=>{"ref"=>"/repositories/11/archival_objects/2119178"}, "external_ids"=>[], "subjects"=>[], "linked_events"=>[], "dates"=>[], "external_documents"=>[], "rights_statements"=>[], "linked_agents"=>[], "restrictions_apply"=>false, "ancestors"=>[], "notes"=>[]}>'}
2018-11-20 15:53:24,950 DEBUG root Working on row 2
2018-11-20 15:53:24,951 DEBUG root Matching top_containers
2018-11-20 15:53:24,951 DEBUG root Container match not found
2018-11-20 15:53:24,951 DEBUG root Container match not found
2018-11-20 15:53:24,951 DEBUG root Container match not found
2018-11-20 15:53:24,952 DEBUG root Container match not found
2018-11-20 15:53:24,952 DEBUG root Container match not found
2018-11-20 15:53:24,952 DEBUG root Container match not found
2018-11-20 15:53:24,952 DEBUG root Calling action function
2018-11-20 15:53:24,958 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:25,379 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "POST /api/repositories/11/archival_objects HTTP/1.1" 200 128
2018-11-20 15:53:25,395 DEBUG root Finishing action function
2018-11-20 15:53:25,410 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:25,841 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "POST /api/repositories/11/events HTTP/1.1" 200 116
2018-11-20 15:53:25,860 DEBUG root Working on row 3
2018-11-20 15:53:25,860 DEBUG root Matching top_containers
2018-11-20 15:53:25,864 DEBUG root Container match not found
2018-11-20 15:53:25,865 DEBUG root Container match not found
2018-11-20 15:53:25,866 DEBUG root Container match not found
2018-11-20 15:53:25,867 DEBUG root Container match not found
2018-11-20 15:53:25,868 DEBUG root Container match not found
2018-11-20 15:53:25,869 DEBUG root Container match not found
2018-11-20 15:53:25,870 DEBUG root Calling action function
2018-11-20 15:53:25,877 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:26,296 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "POST /api/repositories/11/archival_objects HTTP/1.1" 200 128
2018-11-20 15:53:26,312 DEBUG root Finishing action function
2018-11-20 15:53:26,312 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:26,744 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "POST /api/repositories/11/events HTTP/1.1" 200 116
2018-11-20 15:53:26,744 DEBUG root Working on row 4
2018-11-20 15:53:26,744 DEBUG root Matching top_containers
2018-11-20 15:53:26,744 DEBUG root Container match not found
2018-11-20 15:53:26,744 DEBUG root Container match not found
2018-11-20 15:53:26,744 DEBUG root Container match not found
2018-11-20 15:53:26,744 DEBUG root Container match not found
2018-11-20 15:53:26,744 DEBUG root Container match not found
2018-11-20 15:53:26,744 DEBUG root Container match not found
2018-11-20 15:53:26,744 DEBUG root Calling action function
2018-11-20 15:53:26,759 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:27,189 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "POST /api/repositories/11/archival_objects HTTP/1.1" 200 128
2018-11-20 15:53:27,194 DEBUG root Finishing action function
2018-11-20 15:53:27,200 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:27,613 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "POST /api/repositories/11/events HTTP/1.1" 200 116
2018-11-20 15:53:27,613 DEBUG root Working on row 5
2018-11-20 15:53:27,613 DEBUG root Matching top_containers
2018-11-20 15:53:27,613 DEBUG root Container match not found
2018-11-20 15:53:27,613 DEBUG root Container match not found
2018-11-20 15:53:27,613 DEBUG root Container match not found
2018-11-20 15:53:27,613 DEBUG root Container match not found
2018-11-20 15:53:27,613 DEBUG root Container match not found
2018-11-20 15:53:27,613 DEBUG root Container match not found
2018-11-20 15:53:27,613 DEBUG root Calling action function
2018-11-20 15:53:27,629 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:28,075 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "POST /api/repositories/11/archival_objects HTTP/1.1" 200 128
2018-11-20 15:53:28,075 DEBUG root Finishing action function
2018-11-20 15:53:28,096 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:28,521 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "POST /api/repositories/11/events HTTP/1.1" 200 116
2018-11-20 15:53:28,526 DEBUG root Working on row 6
2018-11-20 15:53:28,527 DEBUG root Matching top_containers
2018-11-20 15:53:28,527 DEBUG root Container match not found
2018-11-20 15:53:28,527 DEBUG root Container match not found
2018-11-20 15:53:28,527 DEBUG root Container match not found
2018-11-20 15:53:28,528 DEBUG root Container match not found
2018-11-20 15:53:28,528 DEBUG root Container match not found
2018-11-20 15:53:28,528 DEBUG root Container match not found
2018-11-20 15:53:28,528 DEBUG root Calling action function
2018-11-20 15:53:28,530 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:28,962 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "POST /api/repositories/11/archival_objects HTTP/1.1" 200 128
2018-11-20 15:53:28,977 DEBUG root Finishing action function
2018-11-20 15:53:28,977 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:29,393 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "POST /api/repositories/11/events HTTP/1.1" 200 116
2018-11-20 15:53:29,408 DEBUG root Working on row 7
2018-11-20 15:53:29,408 DEBUG root Matching top_containers
2018-11-20 15:53:29,408 DEBUG root Container match not found
2018-11-20 15:53:29,408 DEBUG root Container match not found
2018-11-20 15:53:29,408 DEBUG root Container match not found
2018-11-20 15:53:29,408 DEBUG root Container match not found
2018-11-20 15:53:29,408 DEBUG root Container match not found
2018-11-20 15:53:29,408 DEBUG root Container match not found
2018-11-20 15:53:29,408 DEBUG root Calling action function
2018-11-20 15:53:29,408 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:29,851 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "POST /api/repositories/11/archival_objects HTTP/1.1" 200 128
2018-11-20 15:53:29,863 DEBUG root Finishing action function
2018-11-20 15:53:29,866 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:30,274 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "POST /api/repositories/11/events HTTP/1.1" 200 116
2018-11-20 15:53:30,274 DEBUG root Working on row 8
2018-11-20 15:53:30,274 DEBUG root Matching top_containers
2018-11-20 15:53:30,274 DEBUG root Container match not found
2018-11-20 15:53:30,274 DEBUG root Container match not found
2018-11-20 15:53:30,274 DEBUG root Container match not found
2018-11-20 15:53:30,274 DEBUG root Container match not found
2018-11-20 15:53:30,274 DEBUG root Container match not found
2018-11-20 15:53:30,274 DEBUG root Container match not found
2018-11-20 15:53:30,274 DEBUG root Calling action function
2018-11-20 15:53:30,290 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:30,695 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "POST /api/repositories/11/archival_objects HTTP/1.1" 200 128
2018-11-20 15:53:30,695 DEBUG root Finishing action function
2018-11-20 15:53:30,695 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:31,111 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "POST /api/repositories/11/events HTTP/1.1" 200 116
2018-11-20 15:53:31,111 DEBUG root Working on row 9
2018-11-20 15:53:31,111 DEBUG root Matching top_containers
2018-11-20 15:53:31,111 DEBUG root Container match not found
2018-11-20 15:53:31,111 DEBUG root Container match not found
2018-11-20 15:53:31,111 DEBUG root Container match not found
2018-11-20 15:53:31,111 DEBUG root Container match not found
2018-11-20 15:53:31,111 DEBUG root Container match not found
2018-11-20 15:53:31,111 DEBUG root Container match not found
2018-11-20 15:53:31,111 DEBUG root Calling action function
2018-11-20 15:53:31,127 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:31,566 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "POST /api/repositories/11/archival_objects HTTP/1.1" 200 128
2018-11-20 15:53:31,572 DEBUG root Finishing action function
2018-11-20 15:53:31,577 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:32,027 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "POST /api/repositories/11/events HTTP/1.1" 200 116
2018-11-20 15:53:32,042 DEBUG root Working on row 10
2018-11-20 15:53:32,042 DEBUG root Matching top_containers
2018-11-20 15:53:32,042 DEBUG root Container match not found
2018-11-20 15:53:32,042 DEBUG root Container match not found
2018-11-20 15:53:32,042 DEBUG root Container match not found
2018-11-20 15:53:32,042 DEBUG root Container match not found
2018-11-20 15:53:32,042 DEBUG root Container match not found
2018-11-20 15:53:32,042 DEBUG root Container match not found
2018-11-20 15:53:32,042 DEBUG root Calling action function
2018-11-20 15:53:32,042 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:32,492 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "POST /api/repositories/11/archival_objects HTTP/1.1" 200 128
2018-11-20 15:53:32,497 DEBUG root Finishing action function
2018-11-20 15:53:32,503 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:32,924 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "POST /api/repositories/11/events HTTP/1.1" 200 116
2018-11-20 15:53:32,940 DEBUG root Working on row 11
2018-11-20 15:53:32,940 DEBUG root Matching top_containers
2018-11-20 15:53:32,940 DEBUG root Container match not found
2018-11-20 15:53:32,940 DEBUG root Container match not found
2018-11-20 15:53:32,940 DEBUG root Container match not found
2018-11-20 15:53:32,940 DEBUG root Container match not found
2018-11-20 15:53:32,940 DEBUG root Container match not found
2018-11-20 15:53:32,940 DEBUG root Container match not found
2018-11-20 15:53:32,940 DEBUG root Calling action function
2018-11-20 15:53:32,940 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:33,377 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "POST /api/repositories/11/archival_objects HTTP/1.1" 200 128
2018-11-20 15:53:33,377 DEBUG root Finishing action function
2018-11-20 15:53:33,397 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:33,842 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "POST /api/repositories/11/events HTTP/1.1" 200 116
2018-11-20 15:53:33,844 DEBUG root Working on row 12
2018-11-20 15:53:33,844 DEBUG root Matching top_containers
2018-11-20 15:53:33,844 DEBUG root Container match not found
2018-11-20 15:53:33,844 DEBUG root Container match not found
2018-11-20 15:53:33,844 DEBUG root Container match not found
2018-11-20 15:53:33,844 DEBUG root Container match not found
2018-11-20 15:53:33,844 DEBUG root Container match not found
2018-11-20 15:53:33,844 DEBUG root Container match not found
2018-11-20 15:53:33,844 DEBUG root Calling action function
2018-11-20 15:53:33,846 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:34,263 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "POST /api/repositories/11/archival_objects HTTP/1.1" 200 128
2018-11-20 15:53:34,279 DEBUG root Finishing action function
2018-11-20 15:53:34,295 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): archivesspace.library.yale.edu
2018-11-20 15:53:35,952 DEBUG urllib3.connectionpool https://archivesspace.library.yale.edu:443 "POST /api/repositories/11/events HTTP/1.1" 500 2470
2018-11-20 15:53:35,958 ERROR root Error: 
Traceback (most recent call last):
  File "C:\Users\asp59\Desktop\born-digital-accessioner-master\born-digital-accessioner-master\born-dig-accessioner.py", line 454, in process_file
    new_event = self.create_event(headers, current_user, updated_component_uri, repo, row[8], row[9], row[10], cgi.escape(row[11]))
  File "C:\Users\asp59\Desktop\born-digital-accessioner-master\born-digital-accessioner-master\born-dig-accessioner.py", line 368, in create_event
    event_post = requests.post(self.api_url.get()+'/repositories/'+repo_num+'/events',headers=header_value,data=event_data).json()
  File "C:\Python36-32\lib\site-packages\requests-2.18.3-py3.6.egg\requests\models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python36-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2018-11-20 15:53:36,047 DEBUG root Update attempts: 12
2018-11-20 15:53:36,047 DEBUG root Updated successfully: 10
2018-11-20 15:53:36,047 DEBUG root Elapsed time: 0:00:15

**Comment by ucancallmealicia** [comment]
Was able to reproduce error. Removed the '%' from the outcome note and was able to successfully upload. Adding a fix to next commit. Changed the `requests` POST param from `data` to `json` and used the event dict rather than `json.dumps(event_dict)` (lines 360-367). Requires `requests` 2.4.2+ (2014)
