### ISSUE TITLE
Date format error

### ISSUE THREAD

**Issue by ucancallmealicia** [ucancallmealicia/born-digital-accessioner#4]
2019-01-23 09:47:46,731 ERROR root Error: 
Traceback (most recent call last):
  File "born-dig-accessioner.py", line 454, in process_file
    new_event = self.create_event(headers, current_user, updated_component_uri, repo, row[8], row[9], row[10], cgi.escape(row[11]))
  File "born-dig-accessioner.py", line 356, in create_event
    date_value = datetime.datetime.strptime(date_value, '%m/%d/%Y').strftime('%Y-%m-%d')
  File "/Users/aliciadetelich/anaconda3/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/Users/aliciadetelich/anaconda3/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '01-25-2018' does not match format '%m/%d/%Y'

**Comment by ucancallmealicia** [comment]
Add support for dates separated by '-'

**Comment by ucancallmealicia** [comment]
Added '-' date format support - lines 356-357 in next commit
